version: '3'
services:
    java:
        volumes:
          - ./:/app
        image: java/nodemon
        ports: ['8080:8080']
        container_name: eleicoesonline_java
        entrypoint: nodemon /app/blockchain-api/index.js & java -Dspring.datasource.url=jdbc:mysql://db/eleicaoonline_dev?createDatabaseIfNotExist=true -Dspring.datasource.username=root -Dspring.datasource.password=  -jar /app/webapp-runner.jar --port 8080 --expand-war /app/eleicoesonline.war
        depends_on:
            - db
    db:  
      image: mysql:5.7
      container_name: db
      entrypoint: ['/entrypoint.sh', '--character-set-server=utf8', '--collation-server=utf8_general_ci']    
      ports: ['3306:3306']
      environment:
        - MYSQL_DATABASE=eleicaoonline_dev
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      volumes:
        - /Users/thiago/Desktop/Study/volume_mysql:/var/lib/mysql